### ISSUE TITLE
Add ability to change ESO Documents directory

### ISSUE THREAD

**Issue by Medallyon** [Medallyon/eso-discord-rich-presence-client#24]
Client might crash if ESO Docs dir is not selected properly from the start. Maybe add instructions on how to flush settings.

**Comment by ryanayoung** [comment]
Agreed.  Wasn't hard to find, but still annoying.  Basically just delete the folder `C:\Users\<USERNAME>\AppData\Local\ESO_Discord_RichPresence_`  Then relaunch the DiscordStatusClient.exe

**Comment by Medallyon** [comment]
Implemented with the [latest release](https://github.com/Medallyon/eso-discord-rich-presence-client/releases/tag/0.4.5).
