### ISSUE TITLE
Level not updating

### ISSUE THREAD

**Issue by Sikksens** [Medallyon/eso-discord-rich-presence-client#25]
Hi there,

The level of my character seems to not be updating, I have priority save enabled and I notice my current quest updates but my level stays the same, Is this known to happen?

**Comment by Medallyon** [comment]
Your overall character information should be updated with the priority save. This includes your current quest status, your character level, and any other information that can be updated. Note that the priority save function is pretty scuffed, which updates at seemingly random intervals (which is something I can't control).
