### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by CuPoTa2010** [Medallyon/eso-discord-rich-presence-client#27]
When I launch mod this error always pop out and Rich Presence doesn't work :c
![изображение](https://user-images.githubusercontent.com/72150777/94704893-141ef080-0349-11eb-91ba-21c602498aa8.png)

**Comment by Medallyon** [comment]
Make sure all the files in the `Discord Rich Presence/Client` folder are there, then try again.

**Comment by CuPoTa2010** [comment]
I redownloaded the mod 2 times but i still get this error. Trying to move files between folders but this doesn't change anything

**Comment by Medallyon** [comment]
What files are in the folder, if you have a screenshot maybe.

Make sure your antivirus doesn't mess with the app.

**Comment by CuPoTa2010** [comment]
![изображение](https://user-images.githubusercontent.com/72150777/94723964-35d8a180-0362-11eb-8848-88b04cd17c05.png)
![изображение](https://user-images.githubusercontent.com/72150777/94723990-412bcd00-0362-11eb-8dd9-a3fa638ebf63.png)
![изображение](https://user-images.githubusercontent.com/72150777/94724018-4a1c9e80-0362-11eb-8fa6-f7b636f0d527.png)
![изображение](https://user-images.githubusercontent.com/72150777/94724039-51dc4300-0362-11eb-950c-06535676a69a.png)
That's all I have in Client folder

**Comment by Medallyon** [comment]
Your screenshots show me that all the files are there, yet it gives you "File not found" error. The only other thing I can suggest is to add the DiscordStatusClient to your Antivirus as an exception or try to move the "Client" folder to another location, like your Desktop, and then try again.
