### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by LucidNyxx** [Medallyon/eso-discord-rich-presence-client#34]
I can't get this to load, Whenever I load it up it gives me an Unhandled exception saying "Access is denied". and then the contents of the folder except the EXE disappear?

its not the AV, I've added exceptions and just disabled it altogether. Tried running as admin with no luck

**Comment by Medallyon** [comment]
Hmm, can you try moving the folder somewhere else (e.g. the Desktop) and run the client from there?

**Comment by LucidNyxx** [comment]
> 
> 
> Hmm, can you try moving the folder somewhere else (e.g. the Desktop) and run the client from there?

Yeah, that worked. It just asked me to locate the ESO folder in documents and I did that and it worked. Strange it doesn't work when you have it inside the ESO folder.

**Comment by whisperity** [comment]
@LucidNyxx So is this okay now? Should this be closed?

**Comment by tokiioKH** [comment]
@whisperity Yes, it works. You can close it now.

**Comment by whisperity** [comment]
Strange. Seems like this might be related to #24 in general... we'll see.
